-- Autogenerated by migration tool on 2022-01-19 12:20:18

-- Resource: error_resource
DROP TABLE IF EXISTS error_resource;

-- Resource: migrate_resource
DROP TABLE IF EXISTS migrate_resource;

-- Resource: panic_resource
DROP TABLE IF EXISTS panic_resource;

-- Resource: slow_resource
DROP TABLE IF EXISTS slow_resource;

-- Resource: very_slow_resource
DROP TABLE IF EXISTS very_slow_resource;
